name: portraits_maker  # portrait_tool에서 변경
description: "A new Flutter project for RPG portraits."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.10.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.0
  image_picker: ^1.2.1
  image: ^4.7.2
  path: ^1.9.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
